### ISSUE TITLE
A monitor is either up or down, but is not configured properly at UptimeRobot.com.

### ISSUE THREAD

**Issue by pandemir** [unreal4u/telegram-bots#3] opened 2020-11-04 11:10 UTC
Tonight @uptimeMonitorBot stopped working for me and several other people. No changes were made to the settings for several years.

Error: A monitor is either up or down, but is not configured properly at UptimeRobot.com. Please check your settings or run /setup to try again.

**Comment by unreal4u** [comment] 2020-11-04 11:13
oh... mm I've been receiving more errors but I thought the functionality was unaffected.

Will check into this, probably has to do with Telegram updated their Bot API but haven't communicated it officially, they introduced some new fields.

Thanks for reporting!

**Comment by unreal4u** [comment] 2020-11-04 11:30
Ok, so the problem is that UptimeRobot doesn't seem to send anymore the date of the event. This should be a pretty easy fix though :)

**Comment by unreal4u** [comment] 2020-11-04 11:32
This should be fixed now, thanks for reporting!

**Closed as completed by unreal4u** 2020-11-04 11:32 UTC
